diagnoses:
  - name: appendicitis
    code:
      system: ICD10
      value: K35
    commonality: .5
    onset_ages:
      - 5+
    mortality: .01
    mortality_window: 1w
    nature: once
    type: problem
  - name: conjunctivitis
    code:
      system: ICD10
      value: H10.33
    commonality: .1
    onset_ages:
      - 0+
    mortality: .0
    nature: reoccurring
    type: problem
