stats: ./bin/patients.yml
control_id:
  seed: 100000
  increment: 1
segments:
  - "./configs/hl7v2/segments/msh.yml"
  - "./configs/hl7v2/segments/evn.yml"
  - "./configs/hl7v2/segments/pid.yml"
  - "./configs/hl7v2/segments/al1.yml"
  - "./configs/hl7v2/segments/pd1.yml"
  - "./configs/hl7v2/segments/pv1.yml"
  - "./configs/hl7v2/segments/zpd.yml"
messages:
  - "./configs/hl7v2/adt_a01.yml"
  - "./configs/hl7v2/adt_a08.yml"
event_definitions:
  - name: allergies
    message_type: ADT
    message_event: A08
    cardinality: 0..*
    triggers: 
      - "conditions[?(@.type=='allergy')]"
    when:
        field: onset_date
        mask: "________HHmmss"
        format: "yyyyMMdd"
    data_sources:
      - type: patient
        filter: demographics
      - type: patient
        filter: "conditions[?(@.type=='allergy')]"