inherit: 
  - ./configs/standard/names.yml
  - ./configs/standard/addresses.yml
  - ./configs/standard/diagnoses.yml
rules:
  counts:
    patients: 10
    providers: 0    
  output: ./bin/patients.yml
identifiers:
  - mask: "#######"
    type: PAT_MRN
distributions:
  race: 
    american_indian_or_alaska_native: .2
    black_or_african_american: .2
    asian: .2
    native_hawaiian_or_pacific_islander: .2
    white: .2
  ethnicity:
    hispanic_or_latino: .33
    non_hispanic_or_latino: .67
  sexuality:
      homosexual: .0165
      bisexual: .018
  gender_identity:
    trans: .00198
    nonbinary: .00099
  ages:
    0-4: .068
    5-17: .189
    18-24: .096
    25-44: .302
    45-64: .22
    65+: .125
  

    